//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervations()
        {
            this.RezervationToRooms = new HashSet<RezervationToRooms>();
        }
    
        public int R_ID { get; set; }
        public int CostumerID { get; set; }
        public int UserID { get; set; }
        public int StadiumID { get; set; }
        public Nullable<System.DateTime> RezervDate { get; set; }
        public decimal Price { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Stadiums Stadiums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RezervationToRooms> RezervationToRooms { get; set; }
        public virtual Users_ Users_ { get; set; }
    }
}
